In [ ]:
!nvidia-smi

Sun Nov 17 21:22:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Switching From Colab to Local M1 MBP

In [ ]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [ ]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [ ]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

## Switch back to Colab

Putting a tensor on the GPU

In [ ]:
import torch

# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

**Exercises**

In [2]:
# Create a random tensor with shape (7,7)

import torch
RANDOM_TENSOR = torch.rand(7, 7)

RANDOM_TENSOR.shape

torch.Size([7, 7])

In [ ]:
# Perform a matrix multiplication on the tensor with another random tensor with shape (1, 7)

RANDOM_TENSOR_2 = torch.rand(1,7)

mat_mul = torch.matmul(RANDOM_TENSOR, RANDOM_TENSOR_2.T)
mat_mul

tensor([[0.9646],
        [1.3812],
        [0.9231],
        [1.4890],
        [1.7523],
        [1.7268],
        [1.6211]])

In [ ]:
# set the random seed to 0 and attempt above again

RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
a = torch.rand(7, 7)
print(f"Tensor 1 Shape: {a.shape}")

b = torch.rand(1, 7)
print(f"Tensor 2 Shape: {b.shape}")

matmul = torch.matmul(a, b.T)
print(matmul)


Tensor 1 Shape: torch.Size([7, 7])
Tensor 2 Shape: torch.Size([1, 7])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [8]:
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)


In [10]:
if torch.cuda.is_available():
    device = "cuda"

print(device)
a = torch.rand(2, 3, device=device)
b = torch.rand(2, 3, device=device)
print(a)
print(b)

cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


In [17]:
res = torch.matmul(a,b.T)
res

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [21]:
torch.max(res)

tensor(0.7668, device='cuda:0')

In [22]:
torch.min(res)

tensor(0.2786, device='cuda:0')

In [25]:
torch.min(res[-1])

tensor(0.6102, device='cuda:0')

In [27]:
torch.max(res[-1])

tensor(0.7343, device='cuda:0')

In [28]:
import torch

# Set the random seed
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor_1 = torch.rand(1, 1, 1, 10)
print(f"Tensor 1: {tensor_1}")
print(f"Tensor 1 Shape: {tensor_1.shape}")

# Remove all singleton dimensions
tensor_2 = tensor_1.squeeze()
print(f"Tensor 2: {tensor_2}")
print(f"Tensor 2 Shape: {tensor_2.shape}")

Tensor 1: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor 1 Shape: torch.Size([1, 1, 1, 10])
Tensor 2: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Tensor 2 Shape: torch.Size([10])
